/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OyunHakkindaRouteImport } from './routes/oyun-hakkinda'
import { Route as EkipIndexRouteImport } from './routes/ekip.index'
import { Route as EkipSlugRouteImport } from './routes/ekip.$slug'
import { Route as OyuncularIndexRouteImport } from './routes/oyuncular.index'
import { Route as OyuncularSlugRouteImport } from './routes/oyuncular.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OyunHakkindaRoute = OyunHakkindaRouteImport.update({
  id: '/oyun-hakkinda',
  path: '/oyun-hakkinda',
  getParentRoute: () => rootRouteImport,
} as any)
const EkipIndexRoute = EkipIndexRouteImport.update({
  id: '/ekip/',
  path: '/ekip/',
  getParentRoute: () => rootRouteImport,
} as any)
const EkipSlugRoute = EkipSlugRouteImport.update({
  id: '/ekip/$slug',
  path: '/ekip/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OyuncularIndexRoute = OyuncularIndexRouteImport.update({
  id: '/oyuncular/',
  path: '/oyuncular/',
  getParentRoute: () => rootRouteImport,
} as any)
const OyuncularSlugRoute = OyuncularSlugRouteImport.update({
  id: '/oyuncular/$slug',
  path: '/oyuncular/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/oyun-hakkinda': typeof OyunHakkindaRoute
  '/ekip/$slug': typeof EkipSlugRoute
  '/oyuncular/$slug': typeof OyuncularSlugRoute
  '/ekip/': typeof EkipIndexRoute
  '/oyuncular/': typeof OyuncularIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/oyun-hakkinda': typeof OyunHakkindaRoute
  '/ekip/$slug': typeof EkipSlugRoute
  '/oyuncular/$slug': typeof OyuncularSlugRoute
  '/ekip': typeof EkipIndexRoute
  '/oyuncular': typeof OyuncularIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/oyun-hakkinda': typeof OyunHakkindaRoute
  '/ekip/$slug': typeof EkipSlugRoute
  '/oyuncular/$slug': typeof OyuncularSlugRoute
  '/ekip/': typeof EkipIndexRoute
  '/oyuncular/': typeof OyuncularIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/oyun-hakkinda'
    | '/ekip/$slug'
    | '/oyuncular/$slug'
    | '/ekip/'
    | '/oyuncular/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/oyun-hakkinda'
    | '/ekip/$slug'
    | '/oyuncular/$slug'
    | '/ekip'
    | '/oyuncular'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/oyun-hakkinda'
    | '/ekip/$slug'
    | '/oyuncular/$slug'
    | '/ekip/'
    | '/oyuncular/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  OyunHakkindaRoute: typeof OyunHakkindaRoute
  EkipSlugRoute: typeof EkipSlugRoute
  OyuncularSlugRoute: typeof OyuncularSlugRoute
  EkipIndexRoute: typeof EkipIndexRoute
  OyuncularIndexRoute: typeof OyuncularIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oyun-hakkinda': {
      id: '/oyun-hakkinda'
      path: '/oyun-hakkinda'
      fullPath: '/oyun-hakkinda'
      preLoaderRoute: typeof OyunHakkindaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekip/': {
      id: '/ekip/'
      path: '/ekip'
      fullPath: '/ekip/'
      preLoaderRoute: typeof EkipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekip/$slug': {
      id: '/ekip/$slug'
      path: '/ekip/$slug'
      fullPath: '/ekip/$slug'
      preLoaderRoute: typeof EkipSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oyuncular/': {
      id: '/oyuncular/'
      path: '/oyuncular'
      fullPath: '/oyuncular/'
      preLoaderRoute: typeof OyuncularIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oyuncular/$slug': {
      id: '/oyuncular/$slug'
      path: '/oyuncular/$slug'
      fullPath: '/oyuncular/$slug'
      preLoaderRoute: typeof OyuncularSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  OyunHakkindaRoute: OyunHakkindaRoute,
  EkipSlugRoute: EkipSlugRoute,
  OyuncularSlugRoute: OyuncularSlugRoute,
  EkipIndexRoute: EkipIndexRoute,
  OyuncularIndexRoute: OyuncularIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
